# Default values for mux-aew.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.

# main DNS name used to access the deployed app in k8s via DNS through an NGINX ingress controller
# if running locally, you may need to edit your "hosts" file under /etc/hosts or the 
# /windows/system32/drivers/etc/hosts file in Windows
# Examples: openrmf.local, demo.openrmf.io, openrmf.mycompany.com
dnsName: openrmf.local

# The Identity Provider URL and Realm, i.e. using Keycloak for AuthN and AuthZ
# Examples: https://keycloak.openrmf.io/auth, http://192.168.11.29:9001/auth
identityProviderURL: http://192.168.11.29:9001/auth
# The Realm to use from the ID provider
identityProviderRealm: openrmf
# The Identity Provider Client Id to use
identityProviderClientId: openrmf

# the namespace to put all of this in
namespace: openrmfdev

# Installation type
# Examples: awseks, minikube
installType: minikube

# versions of container to adjust
# examples: 0.8, 0.8.1, latest
checklistdbImage: 0.8
checklistmsgImage: 0.8
complianceImage: 0.8
compliancemsgImage: 0.8
controlImage: 0.8
controlmsgImage: 0.8
readImage: 0.8
saveImage: 0.8
scoredbImage: 0.8
scoremsgmage: 0.8
scoringImage: 0.8
templateImage: 0.8
templatedbImage: 0.8
uploadImage: 0.8
webuiImage: 0.8.1
natsImage: 1.4.1-linux

# storage class name for PVC
# examples: standard, ebs-sc, efs-sc
storageClass: standard

# API URLs for the web client side calls, used in the web.yaml deployment for the UI
# These are rewritted to the web pods in a ConfigMap for inclusion of client-side API calls
# Examples: 'http://openrmf.local/read', https://read.openrmf.io
readAPI:       http://openrmf.local/read
scoreAPI:      http://openrmf.local/scoring
saveAPI:       http://openrmf.local/save
uploadAPI:     http://openrmf.local/upload
templateAPI:   http://openrmf.local/template
complianceAPI: http://openrmf.local/compliance
controlAPI:    http://openrmf.local/controls

# Service Types for Minikube and AWS separately
# Examples: NodePort, LoadBalancer, etc.
serviceTypeMinikube: NodePort
serviceTypeAWS: LoadBalancer

# AWS ACM Certificate ARN if used
awsACM: arn:aws:acm:us-east-1:xxxxxxxxxxxxxx:certificate/xxxxxxxxxxxxxxxx

# Checklist Database Secret Values
checklistInitDBUser: root
checklistInitDBPassword: mYp2ssw0rd
checklistInitDBName: openrmf
checklistAppUser: openrmf2
checklistAppPassword: openrmf1234!

# Template Database Secret Values
templateInitDBUuser: root
templateInitDBPassword: myp2SSw0rd
templateInitDBName: openrmftemplate
templateAppUser: openrmftemplate2
templateAppPassword: openrmf4321!

# Score Database Secret Values
scoreInitDBUser: root
scoreInitDBPassword: myp2ssw0rd!
scoreInitDBName: openrmfscore
scoreAppUser: openrmfscore2
scoreAppPassword: openrmf9999!