# Default values for mux-aew.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.

# main DNS name used to access the deployed app in k8s via DNS through an ingress controller
dnsName: openrmf.local