# Default values for mux-aew.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.

# main DNS name used to access the deployed app in k8s via DNS through an NGINX ingress controller
# if running locally, you may need to edit your "hosts" file under /etc/hosts or the 
# /windows/system32/drivers/etc/hosts file in Windows
dnsName: demo.openrmf.io

# The Identity Provider URL and Realm, i.e. using Keycloak for AuthN and AuthZ
identityProviderURL: https://keycloak.openrmf.io/auth
# The Realm to use from the ID provider
identityProviderRealm: openrmf
# The Identity Provider Client Id to use
identityProviderClientId: openrmf

# the namespace to put all of this in
namespace: openrmf

# Installation type
# Examples: awseks, minikube
installType: awseks

# versions of container to adjust
# examples: 0.8, 0.8.1, latest
checklistdbImage: 0.8
checklistmsgImage: 0.8
complianceImage: 0.8
compliancemsgImage: 0.8
controlImage: 0.8
controlmsgImage: 0.8
readImage: 0.8
saveImage: 0.8
scoredbImage: 0.8
scoremsgmage: 0.8
scoringImage: 0.8
templateImage: 0.8
templatedbImage: 0.8
uploadImage: 0.8
webuiImage: 0.8.1

natsImage: 1.4.1-linux

# storage class name for PVC
# examples: standard, ebs-sc, efs-sc
storageClass: standard

# API URLs for the web client side calls, used in the web.yaml deployment for the UI
# These are rewritted to the web pods in a ConfigMap for inclusion of client-side API calls
# Examples: 'http://openrmf.local/read', https://read.openrmf.io
readAPI:       https://read.openrmf.io
scoreAPI:      https://scoring.openrmf.io
saveAPI:       https://save.openrmf.io
uploadAPI:     https://upload.openrmf.io
templateAPI:   https://template.openrmf.io
complianceAPI: https://compliance.openrmf.io
controlAPI:    https://controls.openrmf.io

# Service Types for Minikube and AWS separately
# Examples: NodePort, LoadBalancer, etc.
serviceTypeMinikube: NodePort
serviceTypeAWS: LoadBalancer

# AWS ACM Certificate ARN if used
awsACM: arn:aws:acm:us-east-1:xxxxxxxxxxxxxx:certificate/xxxxxxxxxxxxxxxx