version : '3'
 
services:
  mongo:
    image: mongo:4.0.5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: myp2ssw0rd

  nats: 
    image: nats
    restart: always
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222