version : '3'
 
services:
  mongo:
    image: openstig-checklistdb:0.1
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: myp2ssw0rd
      MONGO_INITDB_DATABASE: openstig

  nats: 
    image: nats
    restart: always
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
      
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: myp2ssw0rd