version : '3'
 
services:
  openrmf-web:
    image: openrmf-web:0.7
    ports:
      - 8080:80
    depends_on:
      - openrmfapi-scoring
      - openrmfapi-save
      - openrmfapi-template
      - openrmfapi-upload
      - openrmfapi-read
      - openrmfapi-compliance

  openrmfapi-scoring:
    image: openrmf-api-scoring:0.7
    ports:
      - 8090:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - mongoConnection=mongodb://openrmfscore:openrmf1234!@scoredb/openrmfscore?authSource=openrmfscore
      - mongodb=openrmfscore
      - natsserverurl=nats://natsserver:4222
    depends_on:
      - scoredb
      - natsserver

  openrmfmsg-score:
    image: openrmf-msg-score:0.7
    environment:
      - openrmf-api-read-server=http://openrmfapi-read:8080
      - mongoConnection=mongodb://openrmfscore:openrmf1234!@scoredb/openrmfscore?authSource=openrmfscore
      - mongodb=openrmfscore
      - natsserverurl=nats://natsserver:4222
    depends_on:
      - scoredb
      - natsserver
      - openrmfapi-read
  
  openrmfapi-save:
    image: openrmf-api-save:0.7
    ports:
      - 8082:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - mongoConnection=mongodb://openrmf:openrmf1234!@checklistdb/openrmf?authSource=openrmf
      - mongodb=openrmf
      - natsserverurl=nats://natsserver:4222
    depends_on:
      - openrmfmsg-score
      - checklistdb
      - natsserver

  openrmfapi-template:
    image: openrmf-api-template:0.7
    ports:
      - 8088:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - mongoConnection=mongodb://openrmftemplate:openrmf1234!@templatedb/openrmftemplate?authSource=openrmftemplate
      - mongodb=openrmftemplate
    depends_on:
      - templatedb

  openrmfapi-upload:
    image: openrmf-api-upload:0.7
    ports:
      - 8086:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - mongoConnection=mongodb://openrmf:openrmf1234!@checklistdb/openrmf?authSource=openrmf
      - mongodb=openrmf
      - natsserverurl=nats://natsserver:4222
    depends_on:
      - openrmfmsg-score
      - checklistdb
      - natsserver

  openrmfapi-read:
    image: openrmf-api-read:0.7
    ports:
      - 8084:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - mongoConnection=mongodb://openrmf:openrmf1234!@checklistdb/openrmf?authSource=openrmf
      - mongodb=openrmf
      - openrmf-api-score-server=http://openrmfapi-scoring:8080
      - openrmf-api-compliance-server=http://openrmfapi-compliance:8080
    depends_on:
      - checklistdb
      - openrmfapi-scoring

  openrmfapi-compliance:
    image: openrmf-api-compliance:0.7
    ports:
      - 8092:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - openrmf-api-read-server=http://openrmfapi-read:8080
      - openrmf-api-controls-server=http://openrmfapi-controls:8080
    depends_on:
      - openrmfapi-read
      - openrmfapi-controls

  openrmfapi-controls:
    image: openrmf-api-controls:0.7
    ports:
      - 8094:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080

  checklistdb:
    image: openrmf-checklistdb:0.7
    restart: always
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=myp2ssw0rd
      - MONGO_INITDB_DATABASE=openrmf
    volumes:
      - checklist-data-volume:/data/db

  scoredb:
    image: openrmf-scoredb:0.7
    restart: always
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=myp2ssw0rd
      - MONGO_INITDB_DATABASE=openrmfscore
    volumes:
      - score-data-volume:/data/db

  templatedb:
    image: openrmf-templatedb:0.7
    restart: always
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=myp2ssw0rd
      - MONGO_INITDB_DATABASE=openrmftemplate
    volumes:
      - template-data-volume:/data/db

  natsserver: 
    image: nats
    restart: always
    ports:
      - 4222
      - 6222
      - 8222

# put all the volume listings here for persistent data
volumes:
  template-data-volume:
  checklist-data-volume:
  score-data-volume: