---
# Source: openrmf/templates/checklistdb.yaml
apiVersion: v1
kind: Secret
metadata:
  name: checklistdbsecret
  namespace: openrmfdev
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: openrmf-1.1.0
    app.kubernetes.io/component: checklist-mongodb-secret
    app.kubernetes.io/instance: testnumber2
    app.kubernetes.io/revision: "0"
    app.kubernetes.io/version: 0.8.1
    app.kubernetes.io/managed-by: helm
type: Opaque
data:
  initUsername: root
  initPassword: mYp2ssw0rd
  initDBNname: openrmf
  appConnection: mongodb://openrmf2:openrmf1234!@openrmf-checklistdb/openrmf?authSource=openrmf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: checklistdb-initconfig
  namespace: openrmfdev
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: openrmf-1.1.0
    app.kubernetes.io/component: checklistdb-init-config
    app.kubernetes.io/instance: testnumber2
    app.kubernetes.io/revision: "0"
    app.kubernetes.io/version: 0.8.1
    app.kubernetes.io/managed-by: helm
data:
  mongo-init.js: |
    db.createUser({ user: "openrmf2" , pwd: "openrmf1234!!", roles: [{ "role": "readWrite", "db": "openrmf"}]});
    db.createCollection("Artifacts");
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openrmf-checklistdb
  namespace: openrmfdev
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: openrmf-1.1.0
    app.kubernetes.io/component: checklist-mongodb
    app.kubernetes.io/instance: testnumber2
    app.kubernetes.io/revision: "0"
    app.kubernetes.io/version: 0.8.1
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      run: openrmf-checklistdb
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: openrmf-checklistdb
    spec:
      containers:
      - name: openrmf-checklistdb
        image: mongo:4.0.5
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:  
            secretKeyRef:
              name: checklistdbsecret
              key: initUsername
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:  
            secretKeyRef:
              name: checklistdbsecret
              key: initPassword
        - name: MONGO_INITDB_DATABASE
          valueFrom:  
            secretKeyRef:
              name: checklistdbsecret
              key: initDBNname
        resources:
          requests:
            memory: "500M"
            cpu: "200m"
        volumeMounts:
        - mountPath: /data/db
          name: mongodata-checklistdb
      restartPolicy: Always
      volumes:
      - name: mongodata-checklistdb
        persistentVolumeClaim:
          claimName: openrmf-checklistdb-claim
      - name: initconfig-volume
        configMap:
          name: checklistdb-initconfig
---
apiVersion: v1
kind: Service
metadata:
  name: openrmf-checklistdb
  namespace: openrmfdev
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: openrmf-1.1.0
    app.kubernetes.io/component: checklist-mongodb
    app.kubernetes.io/instance: testnumber2
    app.kubernetes.io/revision: "0"
    app.kubernetes.io/version: 0.8.1
    app.kubernetes.io/managed-by: helm
spec:
  ports:
  - name: mongodb-checklistdb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    run: openrmf-checklistdb
  sessionAffinity: None
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: openrmfdev
  name: openrmf-checklistdb-claim
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: openrmf-1.1.0
    app.kubernetes.io/component: checklist-mongodb
    app.kubernetes.io/instance: testnumber2
    app.kubernetes.io/revision: "0"
    app.kubernetes.io/version: 0.8.1
    app.kubernetes.io/managed-by: helm
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi