{{ if .Values.useprometheusoperator }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: openrmf-audit-api-metrics
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/component: audit-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/revision: "{{ .Release.Revision }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
    {{ .Chart.servicemonitormatchlabelname }}: {{ .Chart.servicemonitormatchlabelvalue }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: audit-api
  endpoints:
  - port: https
    interval: 15s
    path: /metrics
  namespaceSelector:
    matchNames:
    - openrmf
{{ end }}
