apiVersion: v1
kind: Secret
metadata:
  name: checklistdbsecret
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/component: checklist-mongodb-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/revision: "{{ .Release.Revision }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
type: Opaque
data:
  username: {{.Values.checklistdbuser}}
  password: {{.Values.checklistdbpassword}}
  dbname: {{.Values.openrmftemplate}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openrmf-checklistdb
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/component: checklist-mongodb
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/revision: "{{ .Release.Revision }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      run: openrmf-checklistdb
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: openrmf-checklistdb
    spec:
      containers:
      - name: openrmf-checklistdb
        image: cingulara/openrmf-checklistdb:{{.Values.checklistdbImage}}
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:  
            secretKeyRef:
              name: checklistdbsecret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:  
            secretKeyRef:
              name: checklistdbsecret
              key: password
        - name: MONGO_INITDB_DATABASE
          valueFrom:  
            secretKeyRef:
              name: checklistdbsecret
              key: dbname
        resources:
          requests:
            memory: "500M"
            cpu: "200m"
        volumeMounts:
        - mountPath: /data/db
          name: mongodata-checklistdb
      restartPolicy: Always
      volumes:
      - name: mongodata-checklistdb
        persistentVolumeClaim:
          claimName: openrmf-checklistdb-claim
---
apiVersion: v1
kind: Service
metadata:
  name: openrmf-checklistdb
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/component: checklist-mongodb
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/revision: "{{ .Release.Revision }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
spec:
  ports:
  - name: mongodb-checklistdb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    run: openrmf-checklistdb
  sessionAffinity: None
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{.Values.namespace}}
  name: openrmf-checklistdb-claim
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/component: checklist-mongodb
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/revision: "{{ .Release.Revision }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
spec:
  storageClassName: {{.Values.storageClass}}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi