apiVersion: apps/v1
kind: Deployment
metadata:
  name: openrmf-compliance
  namespace: openrmf
  labels:
    app: openrmf
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: Compliance API
    release: {{ .Release.Name }}
    revision: "{{ .Release.Revision }}"
spec:
  selector:
    matchLabels:
      run: openrmf-compliance
  replicas: 1
  template:
    metadata:
      labels:
        run: openrmf-compliance
    spec:
      containers:
      - name: openrmf-compliance
        image: cingulara/openrmf-api-compliance:latest
        ports:
        - name: web-port
          containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: web-port
          initialDelaySeconds: 5
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /healthz
            port: web-port
          initialDelaySeconds: 3
          periodSeconds: 30
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://*:8080
        - name: openrmf-api-read-server
          value: http://openrmf-read:8080
        - name: openrmf-api-controls-server
          value: http://openrmf-controls:8080
        resources:
          limits:
            memory: "750Mi"
            cpu: "500m"
          requests:
            memory: "250Mi"
            cpu: "125m"
---
apiVersion: v1
kind: Service
metadata:
  name: openrmf-compliance
  namespace: openrmf
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: openrmf-compliance
  sessionAffinity: None
  type: NodePort
