apiVersion: apps/v1
kind: Deployment
metadata:
  name: openrmf-jaeger
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/component: jaeger-server-1.17
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/revision: "{{ .Release.Revision }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      run: openrmf-nats
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: openrmf-nats
    spec:
      containers:
      - name: openrmf-nats
        image: jaegertracing/all-in-one: latest
        ports:
        - containerPort: 5778
          protocol: TCP
        - containerPort: 6831
          protocol: TCP
        - containerPort: 16686
          protocol: TCP
        - containerPort: 16687
          protocol: TCP
        - containerPort: 14271
          protocol: TCP
        resources:
          limits:
            memory: "750Mi"
            cpu: "500m"
          requests:
            memory: "250Mi"
            cpu: "250m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: jaegerserver
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/component: jaeger-server-1.17.0
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/revision: "{{ .Release.Revision }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
spec:
  ports:
  - name: jaeger-tcp
    port: 5778
    protocol: TCP
    targetPort: 5778
  - name: jaeger-udp
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: jaeger-querysvc
    port: 16686
    protocol: TCP
    targetPort: 16686
  - name: jaeger-metrics
    port: 16687
    protocol: TCP
    targetPort: 16687
  - name: jaeger-agent-metrics
    port: 14271
    protocol: TCP
    targetPort: 14271
  selector:
    run: openrmf-jaeger
  sessionAffinity: None
  clusterIP: None
