apiVersion: apps/v1
kind: Deployment
metadata:
  name: openrmf-nats
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/component: nats-server-1.4.1
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/revision: "{{ .Release.Revision }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      run: openrmf-nats
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: openrmf-nats
    spec:
      containers:
      - name: openrmf-nats
        image: nats:{{.Values.natsImage}}
        ports:
        - containerPort: 4222
          protocol: TCP
        resources:
          limits:
            memory: "250Mi"
            cpu: "250m"
          requests:
            memory: "125Mi"
            cpu: "125m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: natsserver
  namespace: openrmf
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/component: nats-server-1.4.1
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/revision: "{{ .Release.Revision }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
spec:
  ports:
  - name: nats
    port: 4222
    protocol: TCP
    targetPort: 4222
  selector:
    run: openrmf-nats
  sessionAffinity: None
  clusterIP: None