kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{.Values.namespace}}
  name: report-db-connection-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: report-mongodb
  ingress:
  - ports:
    - port: 27017
    from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: report-nats-message-client
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: report-api