apiVersion: apps/v1
kind: Deployment
metadata:
  name: openrmf-templatedb
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/component: template-mongodb
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/revision: "{{ .Release.Revision }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      run: openrmf-templatedb
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: openrmf-templatedb
    spec:
      containers:
      - name: openrmf-templatedb
        image: cingulara/openrmf-templatedb:{{.Values.templateImage}}
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: myp2ssw0rd
        - name: MONGO_INITDB_DATABASE
          value: openrmftemplate
        resources:
          requests:
            memory: "500M"
            cpu: "200m"
        volumeMounts:
        - mountPath: /data/db
          name: mongodata-templatedb
      restartPolicy: Always
      volumes:
      - name: mongodata-templatedb
        persistentVolumeClaim:
          claimName: openrmf-templatedb-claim
---
apiVersion: v1
kind: Service
metadata:
  name: openrmf-templatedb
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/component: template-mongodb
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/revision: "{{ .Release.Revision }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
spec:
  ports:
  - name: mongodb-templatedb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    run: openrmf-templatedb
  sessionAffinity: None
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{.Values.namespace}}
  name: openrmf-templatedb-claim
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/component: template-mongodb
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/revision: "{{ .Release.Revision }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
spec:
  storageClassName: {{.Values.storageClass}}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi