# put the apis.js into the proper area for the path to call within K8s
apiVersion: v1
kind: ConfigMap
metadata:
  name: openrmf-apiconfig
  namespace: {{.Values.namespace}}
  labels:
    app: openrmf
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: web-ui-apijs
    release: {{ .Release.Name }}
    revision: "{{ .Release.Revision }}"
data:
  apis.js: |
    var readAPI = '{{.Values.readAPI}}'
    var scoreAPI = '{{.Values.scoreAPI}}'
    var saveAPI = '{{.Values.saveAPI}}'
    var uploadAPI = '{{.Values.uploadAPI}}'
    var templateAPI = '{{.Values.templateAPI}}'
    var complianceAPI = '{{.Values.complianceAPI}}'
    var controlAPI = '{{.Values.controlAPI}}'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openrmf-authconfig
  namespace: {{.Values.namespace}}
  labels:
    app: openrmf
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: web-ui-authjs
    release: {{ .Release.Name }}
    revision: "{{ .Release.Revision }}"
data:
  auth.js: |
    var keycloak = Keycloak({ url: '{{.Values.identityProviderURL}}', realm: '{{.Values.identityProviderRealm}}', clientId: '{{.Values.identityProviderClientId}}'});
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openrmf-web
  namespace: {{.Values.namespace}}
  labels:
    app: openrmf
    component: web
spec:
  selector:
    matchLabels:
      run: openrmf-web
  replicas: 1
  template:
    metadata:
      labels:
        run: openrmf-web
    spec:
      containers:
      - name: openrmf-web
        image: cingulara/openrmf-web:{{.Values.webuiImage}}
        volumeMounts:
        - name: apiconfig-volume
          mountPath: /usr/share/nginx/html/js/apis.js
          subPath: apis.js
        - name: authconfig-volume
          mountPath: /usr/share/nginx/html/js/auth.js
          subPath: auth.js
        ports:
        - name: web-port
          containerPort: 80
        resources:
          limits:
            memory: "400M"
            cpu: "500m"
          requests:
            memory: "150M"
            cpu: "100m"
        readinessProbe:
          tcpSocket:
            port: web-port
          initialDelaySeconds: 5
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /status.html
            port: web-port
          initialDelaySeconds: 3
          periodSeconds: 60
      volumes:
        - name: apiconfig-volume
          configMap:
            name: openrmf-apiconfig
        - name: authconfig-volume
          configMap:
            name: openrmf-authconfig
---
apiVersion: v1
kind: Service
metadata:
  name: openrmf-web
  namespace: {{.Values.namespace}}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: openrmf-web
  sessionAffinity: None
  type: {{.Values.serviceType}}