---
# Source: openrmf/templates/compliancemsg.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openrmf-msg-compliance
  namespace: openrmf
  labels:
    app: openrmf
    chart: openrmf-1.0.0
    component: compliance-nats-message-client
    release: release-name
    revision: "0"
spec:
  selector:
    matchLabels:
      run: openrmf-msg-compliance
  replicas: 1
  template:
    metadata:
      labels:
        run: openrmf-msg-compliance
    spec:
      containers:
      - name: openrmf-msg-compliance
        image: cingulara/openrmf-msg-compliance:latest
        ports:
        - containerPort: 8080
        env:
        - name: NATSSERVERURL
          value: nats://natsserver:4222
        resources:
          limits:
            memory: "1Gi"
            cpu: "250m"
          requests:
            memory: "500M"
            cpu: "100m"