apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openrmf-controls-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /openrmf-controls
        backend:
          serviceName: openrmf-controls
          servicePort: 8094