apiVersion: apps/v1
kind: Deployment
metadata:
  name: openrmf-read
  namespace: openrmf
spec:
  selector:
    matchLabels:
      run: openrmf-read
  replicas: 2
  template:
    metadata:
      labels:
        run: openrmf-read
    spec:
      containers:
      - name: openrmf-read
        image: cingulara/openrmf-api-read:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://*:8080
        - name: openrmf-api-score-server
          value: http://openrmfapi-scoring:8080
        - name: openrmf-api-compliance-server
          value: http://openrmfapi-compliance:8080
        - name: mongoConnection
          value: mongodb://openrmf:openrmf1234!@192.168.11.52/openrmf?authSource=openrmf
        - name: mongodb
          value: openrmf
        resources:
          limits:
            memory: "1Gi"
            cpu: "750m"
          requests:
            memory: "500M"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: openrmf-read
  namespace: openrmf
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: openrmf-read
  sessionAffinity: None
  type: NodePort
