apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openrmf-scoring-ingress
  namespace: openrmf
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: scoring.openrmf
    http:
      paths:
      - path: /*
        backend:
          serviceName: openrmf-scoring
          servicePort: 8080