apiVersion: apps/v1
kind: Deployment
metadata:
  name: openrmf-template
  namespace: openrmf
spec:
  selector:
    matchLabels:
      run: openrmf-template
  replicas: 2
  template:
    metadata:
      labels:
        run: openrmf-template
    spec:
      containers:
      - name: openrmf-template
        image: cingulara/openrmf-api-template:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://*:8080
        - name: natsserverurl
          value: nats://natsserver:4222
        - name: mongoConnection
          value: mongodb://openrmftemplate:openrmf1234!@openrmf-templatedb/openrmftemplate?authSource=openrmftemplate
        - name: mongodb
          value: openrmftemplate
        resources:
          limits:
            memory: "1Gi"
            cpu: "750m"
          requests:
            memory: "500M"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: openrmf-template
  namespace: openrmf
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: openrmf-template
  sessionAffinity: None
  type: NodePort
