version : '3'
 
services:
### 1 Web Front End Container
  openrmf-web:
    image: cingulara/openrmf-web:0.12.1
    ports:
      - 8080:80
    depends_on:
      - openrmfapi-scoring
      - openrmfapi-save
      - openrmfapi-template
      - openrmfapi-upload
      - openrmfapi-read
      - openrmfapi-compliance
    networks:
      - openrmf

### 8 API Containers
  openrmfapi-scoring:
    image: cingulara/openrmf-api-scoring:0.12
    ports:
      - 8090:8080
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - MONGODBCONNECTION=mongodb://openrmfscore:openrmf1234!@scoredb/openrmfscore?authSource=openrmfscore
      - MONGODB=openrmfscore
    depends_on:
      - scoredb
    networks:
      - openrmf
  
  openrmfapi-save:
    image: cingulara/openrmf-api-save:0.12
    ports:
      - 8082:8080
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - MONGODBCONNECTION=mongodb://openrmf:openrmf1234!@checklistdb/openrmf?authSource=openrmf
      - MONGODB=openrmf
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - openrmfmsg-score
      - checklistdb
      - natsserver
    networks:
      - openrmf

  openrmfapi-template:
    image: cingulara/openrmf-api-template:0.11.2
    ports:
      - 8088:8080
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - MONGODBCONNECTION=mongodb://openrmftemplate:openrmf1234!@templatedb/openrmftemplate?authSource=openrmftemplate
      - MONGODB=openrmftemplate
    depends_on:
      - templatedb
    networks:
      - openrmf

  openrmfapi-upload:
    image: cingulara/openrmf-api-upload:0.12
    ports:
      - 8086:8080
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - MONGODBCONNECTION=mongodb://openrmf:openrmf1234!@checklistdb/openrmf?authSource=openrmf
      - MONGODB=openrmf
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - openrmfmsg-score
      - checklistdb
      - natsserver
    networks:
      - openrmf

  openrmfapi-read:
    image: cingulara/openrmf-api-read:0.12
    ports:
      - 8084:8080
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - MONGODBCONNECTION=mongodb://openrmf:openrmf1234!@checklistdb/openrmf?authSource=openrmf
      - MONGODB=openrmf
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - checklistdb
    networks:
      - openrmf

  openrmfapi-compliance:
    image: cingulara/openrmf-api-compliance:0.11
    ports:
      - 8092:8080
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - NATSSERVERURL=nats://natsserver:4222
    networks:
      - openrmf

  openrmfapi-controls:
    image: cingulara/openrmf-api-controls:0.11
    ports:
      - 8094:8080
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - NATSSERVERURL=nats://natsserver:4222
    networks:
      - openrmf

  openrmfapi-audit:
    image: cingulara/openrmf-api-audit:0.11
    ports:
      - 8096:8080
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - MONGODBCONNECTION=mongodb://openrmfaudit:openrmf1234!@auditdb/openrmfaudit?authSource=openrmfaudit
      - MONGODB=openrmfaudit
      - NATSSERVERURL=nats://natsserver:4222
    networks:
      - openrmf

### 7 Messaging Containers
  openrmfmsg-score:
    image: cingulara/openrmf-msg-score:0.12
    environment:
      - MONGODBCONNECTION=mongodb://openrmfscore:openrmf1234!@scoredb/openrmfscore?authSource=openrmfscore
      - MONGODB=openrmfscore
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - scoredb
      - natsserver
    networks:
      - openrmf

  openrmfmsg-checklist:
    image: cingulara/openrmf-msg-checklist:0.12
    environment:
      - MONGODBCONNECTION=mongodb://openrmf:openrmf1234!@checklistdb/openrmf?authSource=openrmf
      - MONGODB=openrmf
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - checklistdb
      - natsserver
    networks:
      - openrmf

  openrmfmsg-compliance:
    image: cingulara/openrmf-msg-compliance:0.11
    environment:
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - natsserver
    networks:
      - openrmf

  openrmfmsg-controls:
    image: cingulara/openrmf-msg-controls:0.11
    environment:
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - natsserver
    networks:
      - openrmf

  openrmfmsg-template:
    image: cingulara/openrmf-msg-template:0.11
    environment:
      - MONGODBCONNECTION=mongodb://openrmftemplate:openrmf1234!@templatedb/openrmftemplate?authSource=openrmftemplate
      - MONGODB=openrmftemplate
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - templatedb
      - natsserver
    networks:
      - openrmf

  openrmfmsg-system:
    image: cingulara/openrmf-msg-system:0.12
    environment:
      - MONGODBCONNECTION=mongodb://openrmf:openrmf1234!@checklistdb/openrmf?authSource=openrmf
      - MONGODB=openrmf
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - checklistdb
      - natsserver
    networks:
      - openrmf

  openrmfmsg-audit:
    image: cingulara/openrmf-msg-audit:0.11
    environment:
      - MONGODBCONNECTION=mongodb://openrmfaudit:openrmf1234!@auditdb/openrmfaudit?authSource=openrmfaudit
      - MONGODB=openrmfaudit
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - checklistdb
      - natsserver
    networks:
      - openrmf

### 4 MongoDB Containers
  checklistdb:
    image: mongo:4.0.5
    restart: always
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=myp2ssw0rd
      - MONGO_INITDB_DATABASE=openrmf
    volumes:
      - checklist-data-volume:/data/db
      - ./initializeChecklist.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - openrmf

  scoredb:
    image: mongo:4.0.5
    restart: always
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=myp2ssw0rd
      - MONGO_INITDB_DATABASE=openrmfscore
    volumes:
      - score-data-volume:/data/db
      - ./initializeScore.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - openrmf

  templatedb:
    image: mongo:4.0.5
    restart: always
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=myp2ssw0rd
      - MONGO_INITDB_DATABASE=openrmftemplate
    volumes:
      - template-data-volume:/data/db
      - ./initializeTemplate.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - openrmf

  auditdb:
    image: mongo:4.0.5
    restart: always
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=myp2ssw0rd
      - MONGO_INITDB_DATABASE=openrmfaudit
    volumes:
      - audit-data-volume:/data/db
      - ./initializeAudit.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - openrmf

### NATS messaging container (internal)
  natsserver: 
    image: nats:2.1.2-linux
    command: -m 8222
    restart: always
    ports:
      - 4222
      - 6222
      - 8222
    networks:
      - openrmf

### Metrics
  natspromexporter: 
    image: synadia/prometheus-nats-exporter:latest
    command: -DV -varz http://natsserver:8222
    restart: always
    ports:
      - 7777
    networks:
      - openrmf

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    restart: always
    ports:
      - 9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - openrmf

  grafana: 
    image: grafana/grafana
    #command:
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=1qaz2WSX3edc4RFVgr@fana
    restart: always
    ports:
      - 3000:3000
    networks:
      - openrmf

### put all the volume listings here for persistent data
volumes:
  template-data-volume:
  checklist-data-volume:
  score-data-volume:
  audit-data-volume:

### put all the networks here
networks:
  openrmf:
